name: buddy_mobile
description: BUDDY Personal AI Assistant - Mobile App
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # HTTP & WebSockets
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Audio & Voice
  flutter_sound: ^9.2.13
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  audio_waveforms: ^1.0.4
  
  # Storage & Database
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI & Animations
  lottie: ^2.7.0
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  
  # Network Discovery & Sync
  network_info_plus: ^4.0.2
  connectivity_plus: ^5.0.1
  
  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Utils
  uuid: ^4.0.0
  intl: ^0.18.1
  logger: ^2.0.1
  
  # Platform Integration
  flutter_local_notifications: ^15.1.1
  quick_actions: ^1.0.6
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
    - assets/models/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700